apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-station-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/mnt/data"